log_level: debug
access_log:
commands:
  - name: "trigger"
    target: "trigger-test"
    type: "yomama"
    exec: "echo yomama"
    validate: false
    schema-type: "avro"
    schema: "test.avsc"
  - name: "exec"
    target: "exec-test"
    type: "http"
    exec: "./test.sh"
    validate: true
    schema-type: "json"
    schema: "./schema/test.avsc"