log_level: debug
jwks_url: "https://url/.well-known/jwks.json"
access_log:
commands:
  - name: "trigger"
    protocol: "pubsub"
    target: "dev-trigger-task"
    type: "exec"
    exec: "echo yomama"
    validate: false
    schema-type: "avro"
    schema: "test.avsc"
  - name: "exec"
    target: "exec-test"
    type: "exec"
    exec: "echo HelloWorld!"
    validate: true
    schema-type: "json"
    schema: "./schema/test.avsc"
  - name: "deployfrontend"
    protocol: "http"
    target: "/deploy/frontend"
    type: "bash"
    exec: "./deploy-frontend.sh"
    authentication: true
    validate-claim: 
      role: 
        - admin
        - employee
        - engineer
      scope: 
        - user:read_write
    validate: true
    schema-type: "json"
    schema: "./schema/deploy-frontend.json"